1. Bag of Words Model

In [2]:
pip install keras


Note: you may need to restart the kernel to use updated packages.


In [1]:
from keras.preprocessing.text import Tokenizer

ModuleNotFoundError: No module named 'keras.preprocessing.text'

In [3]:
text = ['There was a man',
        'The man had a dog',
        'The dog and the man walker']

In [4]:
model = Tokenizer()
model.fit_on_texts(text)

In [6]:
print(f"Key : {list(model.word_index.keys())}")
rep = model.texts_to_matrix(text, mode = 'count')
print(rep)

Key : ['man', 'the', 'a', 'dog', 'there', 'was', 'had', 'and', 'walker']
[[0. 1. 0. 1. 0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0. 0. 1. 0. 0.]
 [0. 1. 2. 0. 1. 0. 0. 0. 1. 1.]]


2. Create a Bag of Words Model with Sklearn

In [7]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [8]:
sentence_1 = "This is a good job. I will not miss it for anything"
sentence_2 = "This is not good at all"

In [9]:
CountVec = CountVectorizer(ngram_range=(1, 1), stop_words= 'english')

In [10]:
#Transform
Count_data = CountVec.fit_transform([sentence_1, sentence_2])
print(CountVec)
print(Count_data)

CountVectorizer(stop_words='english')
  (0, 0)	1
  (0, 1)	1
  (0, 2)	1
  (1, 0)	1


In [13]:
cv_dataframe = pd.DataFrame(Count_data.toarray(), columns= CountVec.get_feature_names_out())
print(cv_dataframe)

   good  job  miss
0     1    1     1
1     1    0     0


3. Feature Extraction with TF - IDF vectorizer

In [14]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [15]:
sentence_1 = "This is a good job. I will not miss it for anything"
sentence_2 = "This is not good at all"

In [16]:
# Without smooth IDF
print("Without Smoothing:")
# Define TF - IDF
tf_idf_vec = TfidfVectorizer(use_idf= True, smooth_idf= False,
                             ngram_range=(1,1), stop_words = 'english') # to use only bigrams ngram_range=(2,2)

Without Smoothing:


In [18]:
# Transform
tf_idf_data = tf_idf_vec.fit_transform([sentence_1, sentence_2])

In [21]:
# Create dataframe
tf_idf_dataframe = pd.DataFrame(tf_idf_data.toarray(), columns = tf_idf_vec.get_feature_names_out())
print(tf_idf_dataframe)
print("\n")

       good       job      miss
0  0.385372  0.652491  0.652491
1  1.000000  0.000000  0.000000




In [25]:
# With smooth
tf_idf_vec_smooth = TfidfVectorizer(use_idf=True,
                                    smooth_idf=True,
                                    ngram_range=(1,1),
                                    stop_words='english')

In [26]:
tf_idf_data_smooth = tf_idf_vec_smooth.fit_transform([sentence_1, sentence_2])

In [27]:
print("With Smoothing:")
tf_idf_dataframe_smooth = pd.DataFrame(tf_idf_data_smooth.toarray(), columns=tf_idf_vec_smooth.get_feature_names_out())
print(tf_idf_dataframe_smooth)

With Smoothing:
       good       job      miss
0  0.449436  0.631667  0.631667
1  1.000000  0.000000  0.000000


4. Supervied Classification

4.1 EDA

In [28]:
import os
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [30]:
from IPython.display import Markdown, display
def printmd(string):
  display(Markdown(string))
printmd('**bold**')

**bold**

In [ ]:
data_path = ""

4.1.1 Checking for missing values

4.1.2 Calculating number of comments under each label

4.1.3 Calculating number of comments having multiple labels

4.1.4 WordCloud representation of most used words in each category of comments

4.2 Data Pre - Processing

4.2.1 Cleaning Data

4.2.2 Removing Stop Words

4.2.3 Stemming

4.2.4 Train - Test Split

4.2.5 TF - IDF

4.3 Multi - Label Classification

4.3.1 Multiple Binary Classifications - (One Vs Rest Classifier)

4.3.2 Multiple Binary Classifications - (Binary Relevance)

4.3.3 Classifier Chanins

4.3.4 Label Powerset

4.3.5 Adapted Algorithm